// Models for Candidates API

// Candidate Status Constants
const CANDIDATE_STATUSES = {
  ALL: 'ALL',
  PENDING: 'PENDING',
  ACTIVE: 'Active',
  INACTIVE: 'Inactive',
  REJECTED: 'Rejected',
  APPLIED: 'APPLIED',
  INVITED: 'INVITED',
  MANUALLY_INVITED: 'MANUALLY_INVITED',
  RESUME_REJECTED: 'RESUME_REJECTED',
  RECOMMENDED: 'RECOMMENDED',
  NOT_RECOMMENDED: 'NOT_RECOMMENDED',
  CAUTIOUSLY_RECOMMENDED: 'CAUTIOUSLY_RECOMMENDED',
  TEST_STARTED: 'TEST_STARTED',
  IN_PROGRESS: 'IN_PROGRESS',
  TEST_COMPLETED: 'TEST_COMPLETED',
  EXPIRED: 'EXPIRED',
  UNATTENDED: 'UNATTENDED',
  NETWORK_DISCONNECTED: 'NETWORK_DISCONNECTED',
  ROUND1: 'ROUND1',
  ROUND2: 'ROUND2',
  ROUND3: 'ROUND3',
  ROUND4: 'ROUND4',
  NETWORK_ISSUE: 'NETWORK_ISSUE'
};

const CANDIDATE_STATUS_VALUES = Object.values(CANDIDATE_STATUSES);

// Recommendation Status Constants
const RECOMMENDATION_STATUSES = {
  RECOMMENDED: 'Recommended',
  NOT_RECOMMENDED: 'Not-Recommended',
  CAUTIOUSLY_RECOMMENDED: 'Cautiously Recommended'
};

// Link Types
const LINK_TYPES = {
  PRIVATE: 'PRIVATE',
  PUBLIC: 'PUBLIC'
};

// Assessment Rounds
const ASSESSMENT_ROUNDS = {
  ROUND_1: 1,
  ROUND_2: 2,
  ROUND_3: 3,
  ROUND_4: 4
};

module.exports = {
  CANDIDATE_STATUSES,
  CANDIDATE_STATUS_VALUES,
  RECOMMENDATION_STATUSES,
  LINK_TYPES,
  ASSESSMENT_ROUNDS
};
